# Generated by Django 4.2.1 on 2023-06-01 04:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('affiliate_id_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_affiliate', models.CharField(max_length=50)),
                ('status_affiliate', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DISABLED', 'DISABLED')], default='ACTIVE', max_length=20)),
                ('date_joined_affiliate', models.DateField(auto_now_add=True)),
                ('email_affiliate', models.EmailField(max_length=75)),
                ('phone_number_affiliate', models.TextField(max_length=20)),
                ('address_affiliate', models.CharField(max_length=100)),
                ('city_affiliate', models.CharField(max_length=100)),
                ('zip_code_affiliate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('event_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('IN PROGRESS', 'IN PROGRESS'), ('CANCELLED', 'CANCELLED'), ('POSTPONED', 'POSTPONED')], default='ACTIVE', max_length=25)),
                ('event_name', models.CharField(max_length=100, unique=True)),
                ('event_date_created', models.DateField(auto_now=True)),
                ('event_date', models.DateField()),
                ('event_size', models.CharField(choices=[('10-50', 50), ('50-100', 100), ('100-200', 200), ('200-500', 500)], default='50-100', max_length=10)),
                ('event_location', models.CharField(max_length=100)),
                ('event_address', models.CharField(max_length=100)),
                ('event_phone_number', models.CharField(max_length=20)),
                ('event_host_affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='PlanIFYWOD.affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status_user', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DISABLED', 'DISABLED')], default='ACTIVE', max_length=20)),
                ('date_joined_user', models.DateField(auto_now_add=True)),
                ('first_name_user', models.CharField(max_length=25)),
                ('last_name_user', models.CharField(max_length=25)),
                ('age_user', models.IntegerField()),
                ('email_user', models.EmailField(max_length=75)),
                ('phone_number_user', models.TextField(max_length=20)),
                ('address_user', models.CharField(max_length=100)),
                ('city_user', models.CharField(max_length=100)),
                ('zip_code_user', models.CharField(max_length=100)),
                ('host_user', models.BooleanField()),
                ('athlete_user', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('event_joing_date', models.DateField(auto_created=True)),
                ('participants', models.AutoField(primary_key=True, serialize=False)),
                ('email_of_athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='PlanIFYWOD.useraccount')),
                ('event_id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='PlanIFYWOD.event')),
                ('first_name_of_athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='PlanIFYWOD.useraccount')),
                ('last_name_of_athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='PlanIFYWOD.useraccount')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_host_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='PlanIFYWOD.useraccount'),
        ),
        migrations.CreateModel(
            name='AffiliateMembers',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name_of_member', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='+', to='PlanIFYWOD.useraccount')),
                ('id_of_user', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='+', to='PlanIFYWOD.useraccount')),
                ('last_name_of_member', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='+', to='PlanIFYWOD.useraccount')),
                ('name_of_affiliate', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='+', to='PlanIFYWOD.affiliate')),
            ],
        ),
    ]
