# Generated by Django 4.2.1 on 2023-06-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0002_useraccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
