# Generated by Django 4.2.1 on 2023-07-13 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0002_alter_eventparticipant_event_join_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventparticipant',
            old_name='event_name',
            new_name='event_name_id',
        ),
    ]
