# Generated by Django 4.2.1 on 2023-07-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0003_rename_event_name_eventparticipant_event_name_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventparticipant',
            old_name='event_name_id',
            new_name='event_name',
        ),
    ]
