# Generated by Django 4.2.1 on 2023-06-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0003_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='bio_affiliate',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_bio',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='phone_number_affiliate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number_user',
            field=models.CharField(max_length=20),
        ),
    ]
