# Generated by Django 4.2.1 on 2023-07-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0004_rename_event_name_id_eventparticipant_event_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
