# Generated by Django 4.2.1 on 2023-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0004_affiliate_bio_affiliate_useraccount_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
