# Generated by Django 4.2.1 on 2023-07-13 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0005_delete_eventparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('participant', models.AutoField(primary_key=True, serialize=False)),
                ('first_name_of_participant', models.CharField(max_length=100, null=True)),
                ('last_name_of_participant', models.CharField(max_length=100, null=True)),
                ('birthday_of_participant', models.DateField(blank=True, null=True)),
                ('gender_of_participant', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25, null=True)),
                ('email_of_participant', models.EmailField(max_length=100, null=True)),
                ('address_of_participant', models.CharField(max_length=50, null=True)),
                ('city_of_participant', models.CharField(max_length=50, null=True)),
                ('state_of_participant', models.CharField(max_length=2, null=True)),
                ('zip_code_of_participant', models.IntegerField(null=True)),
                ('event_join_date', models.DateField(auto_now_add=True)),
                ('role', models.CharField(choices=[('Athlete', 'Athlete'), ('Judge', 'Judge'), ('General', 'General')], max_length=15, null=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.event')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.eventteam')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.useraccount')),
            ],
        ),
    ]
