# Generated by Django 4.2.1 on 2023-07-13 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0007_alter_eventparticipant_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='event_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.event'),
        ),
    ]
