# Generated by Django 4.2.1 on 2023-06-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0008_alter_useraccount_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AffiliateMembers',
            new_name='AffiliateMember',
        ),
    ]
