# Generated by Django 4.2.1 on 2023-07-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0008_alter_eventparticipant_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='class_type',
            field=models.CharField(choices=[('Rx', 'Rx'), ('Scaled', 'Scaled')], default='Rx', max_length=10),
            preserve_default=False,
        ),
    ]
