# Generated by Django 4.2.1 on 2023-06-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0009_rename_affiliatemembers_affiliatemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
