# Generated by Django 4.2.1 on 2023-07-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0009_eventparticipant_class_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventworkout',
            old_name='event',
            new_name='event_id',
        ),
    ]
