# Generated by Django 4.2.1 on 2023-07-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0010_rename_event_eventworkout_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventworkout',
            old_name='event_id',
            new_name='event',
        ),
    ]
