# Generated by Django 4.2.1 on 2023-07-20 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlanIFYWOD', '0011_rename_event_id_eventworkout_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.event')),
                ('user', models.OneToOneField(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
