# Generated by Django 4.2.1 on 2023-06-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0012_alter_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_host_affiliate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='PlanIFYWOD.affiliate'),
            preserve_default=False,
        ),
    ]
