# Generated by Django 4.2.1 on 2023-06-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0014_alter_event_event_host_affiliate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_host_affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='PlanIFYWOD.affiliate'),
        ),
    ]
