# Generated by Django 4.2.1 on 2023-06-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0016_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='address_user',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='age_user',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='city_user',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email_user',
            field=models.EmailField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='first_name_user',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='host_user',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name_user',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number_user',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='status_user',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DISABLED', 'DISABLED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_bio',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='zip_code_user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
