# Generated by Django 4.2.1 on 2023-06-06 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlanIFYWOD', '0019_alter_useraccount_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_vendor', models.CharField(max_length=100)),
                ('description_vendor', models.TextField(max_length=500)),
                ('email_vendor', models.EmailField(blank=True, max_length=75)),
                ('phone_number_vendor', models.CharField(blank=True, max_length=20)),
                ('address_vendor', models.CharField(blank=True, max_length=100)),
                ('city_vendor', models.CharField(blank=True, max_length=100)),
                ('zip_code_vendor', models.CharField(blank=True, max_length=100)),
                ('webiste_vendor', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='affiliate',
            name='website_affiliate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliatemember',
            name='approved_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affiliatemember',
            name='date_approved',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='affiliatemember',
            name='date_requested_to_join',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_price_athlete',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='event_price_general',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='event_prizes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='event_promo_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='event_registration_date_close',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_registration_date_open',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_tshirts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.TextField(choices=[('Individual', 'Individual'), ('Team', 'Team'), ('Coed', 'Coed')], default='Individual', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='event_vendors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='event_waiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='event_waiver_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='gener_user',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=15),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='vendor_user',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='athlete_user',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='host_user',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventWorkOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('workout_type', models.CharField(choices=[('Every Minute On The Minute(EMOM)', 'EMOM'), ('As Many Reps As Possible (AMRAP)', 'AMRAP'), ('For Time', 'Time'), ('Tabata', 'Tabata')], max_length=50)),
                ('workout_description', models.TextField(blank=True, max_length=250, null=True)),
                ('workout_time', models.TimeField(blank=True, null=True)),
                ('workout_floater', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventVendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.event')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.vendor')),
            ],
        ),
    ]
