# Generated by Django 4.2.1 on 2023-06-07 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0020_vendor_affiliate_website_affiliate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='email_of_athlete',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='email', to='PlanIFYWOD.useraccount'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='first_name_of_athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_name', to='PlanIFYWOD.useraccount'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='last_name_of_athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_name', to='PlanIFYWOD.useraccount'),
        ),
    ]
