# Generated by Django 4.2.1 on 2023-06-07 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0021_alter_eventparticipant_email_of_athlete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='email_of_athlete',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.event'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='first_name_of_athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.useraccount'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='last_name_of_athlete',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
