# Generated by Django 4.2.1 on 2023-06-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0022_alter_eventparticipant_email_of_athlete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_host_user',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.useraccount'),
        ),
    ]
