# Generated by Django 4.2.1 on 2023-06-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0024_alter_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventworkout',
            name='workout_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
