# Generated by Django 4.2.1 on 2023-07-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0025_eventworkout_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventworkout',
            name='workout_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
