# Generated by Django 4.2.1 on 2023-07-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0027_eventworkout_workout_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
