# Generated by Django 4.2.1 on 2023-07-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0028_event_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_start_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
