# Generated by Django 4.2.1 on 2023-07-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0030_alter_event_event_registration_date_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='affiliate_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='athlete_user_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='host_user_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='vendor_user_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DISABLED', 'DISABLED')], default='ACTIVE', max_length=25),
        ),
    ]
