# Generated by Django 4.2.1 on 2023-07-08 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0031_affiliate_affiliate_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHelp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Judge', 'Judge'), ('MC', 'MC'), ('General', 'General')], max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.event')),
            ],
        ),
    ]
