# Generated by Django 4.2.1 on 2023-07-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0033_event_event_country_event_event_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(default='generic_workout.jpeg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_long_description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
