# Generated by Django 4.2.1 on 2023-07-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0034_event_event_banner_event_event_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_registration_date_close',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_registration_date_open',
            field=models.DateField(blank=True, null=True),
        ),
    ]
