# Generated by Django 4.2.1 on 2023-07-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0035_event_event_start_time_alter_event_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
    ]
