# Generated by Django 4.2.1 on 2023-07-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0036_alter_event_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_img'),
        ),
    ]
