# Generated by Django 4.2.1 on 2023-07-09 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0037_alter_event_event_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanIFYWOD.useraccount'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='first_name_of_athlete',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
