# Generated by Django 4.2.1 on 2023-07-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0038_eventparticipant_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
