# Generated by Django 4.2.1 on 2023-07-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0039_alter_event_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
    ]
