# Generated by Django 4.2.1 on 2023-07-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIFYWOD', '0041_event_event_tshirt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
